# Generated by Django 4.2.2 on 2023-08-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Навыки')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('number_of_employees', models.IntegerField(verbose_name='Количество сотрудников')),
                ('is_hunting', models.BooleanField(default=True, verbose_name='Ищет сотрудников')),
                ('employee', models.ManyToManyField(blank=True, to='worker.worker', verbose_name='Работники')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вакансия')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('description', models.TextField(default='Нет описания', verbose_name='Описание')),
                ('work_experience', models.IntegerField(blank=True, null=True, verbose_name='Опыт работы')),
                ('type_of_employement', models.CharField(choices=[('f', 'Полный рабочий день'), ('p', 'Неполный рабочий день'), ('d', 'Сдельная работа')], default='f', max_length=100, verbose_name='Тип занятости')),
                ('is_relevant', models.BooleanField(default=True, verbose_name='Актуально')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
                ('candidate', models.ManyToManyField(blank=True, to='worker.worker')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='категория')),
                ('skill', models.ManyToManyField(blank=True, to='core.skill', verbose_name='Навыки')),
                ('view_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['salary'],
                'unique_together': {('title', 'email')},
            },
        ),
    ]
