# Generated by Django 4.2.2 on 2023-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_resume_previous_employment'),
        ('core', '0005_category_alter_vacancy_options_vacancy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(blank=True, to='worker.worker'),
        ),
        migrations.AddField(
            model_name='company',
            name='founding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Нет описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вакансия'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
    ]
