# Generated by Django 4.2.2 on 2023-07-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_alter_resume_previous_employment'),
        ('core', '0006_company_employee_company_founding_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(blank=True, to='worker.worker', verbose_name='Работники'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_hunting',
            field=models.BooleanField(default=True, verbose_name='Ищет сотрудников'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
