# Generated by Django 4.2.2 on 2023-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_company_address_alter_company_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Навыки')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type_of_employement',
            field=models.CharField(choices=[('f', 'Полный рабочий день'), ('p', 'Неполный рабочий день'), ('d', 'Сдельная работа')], default='f', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='core.skill'),
        ),
    ]
