# Generated by Django 4.2.2 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skill_vacancy_type_of_employement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_employement',
            field=models.CharField(choices=[('f', 'Полный рабочий день'), ('p', 'Неполный рабочий день'), ('d', 'Сдельная работа')], default='f', max_length=100, verbose_name='Тип занятости'),
        ),
    ]
