# Generated by Django 4.2.2 on 2023-07-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vacancy_type_of_employement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Навыки'),
        ),
    ]
