# Generated by Django 4.2.2 on 2023-08-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Желаемая зарплата')),
                ('is_searching', models.BooleanField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Профессия')),
                ('education_degree', models.CharField(max_length=200, verbose_name='Образование')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы')),
                ('previous_employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предыдущее место работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Фото сотрудника')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
