# Generated by Django 4.2.2 on 2023-06-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('education_degree', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('previous_employment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='worker.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
