# Generated by Django 4.2.2 on 2023-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_resume_delete_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='previous_employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
